### ISSUE TITLE
Serialization problems

### ISSUE THREAD

**Issue by tzjtatata** [danielhavir/capsule-network#1]
Hello,
It seems like that there is no Serialization for this work.
Do you have serialization function or patch?

---update---
there is.
Sorry about that.= =

**Comment by danielhavir** [comment]
Thanks for your comment, yes the model is serialized. Alternatively, you can only save the weights instead of the whole model, see [Serialization in PyTorch](http://pytorch.org/docs/master/notes/serialization.html).
