### ISSUE TITLE
Why is line 45 needed in capsules.py?

### ISSUE THREAD

**Issue by udion** [danielhavir/capsule-network#4]
Why is line 45 needed in capsules.py, is it not redundant? we can directly do 46.

**Comment by danielhavir** [comment]
Very good question! I wasn't 100% sure the reshaping will be always done correctly (i.e. along the right dimension) if it's just `out.view(out.size(0), -1, dim_caps)` so I explicitly added line 45 to ensure the right operation. You want to reshape from the channels dimension. In some cases, it might reshape it in a different way than intended unless you specify, how it should be done - `(batch_size, channels, height, width) -> (batch_size, channels/dim_caps, height, width, dim_caps) -> (batch_size, -1, dim_caps)`
Even though, I did a few sanity checks which mostly agreed that line 45 might be redundant, I just couldn't prove it never needs to be there. 
Lastly, reshaping is not an expensive operation and it also helped me with the intuition on why it is reshaped that way.

**Comment by zhengzh** [comment]
@danielhavir `view` only change the  shape of the tenor but not the data, if you want to reshape from the channel's dimension, firstly, you should use `permute` to change the order of the dimensions, then use `reshape` to reshape it. like this
```
out = out.permute(0, 2, 3, 1)
out = out.reshape(out.size(0), -1, self.dim_caps)
```

**Comment by danielhavir** [comment]
I know I could have used `permute`, but A) that will not speed things up and B) will not help with the intuition and readability. As I say above, reshaping is not an expensive operation and I like that this is more explicit and clear on how the dimensionality changes.
