### ISSUE TITLE
How does this compares to the other projects

### ISSUE THREAD

**Issue by elgalu** [danielhavir/capsule-network#6]
Hi, How does this compares to the other projects?

- https://github.com/gram-ai/capsule-networks
- https://github.com/higgsfield/Capsule-Network-Tutorial
- https://github.com/danielhavir/capsule-network (this one)
- https://github.com/jindongwang/Pytorch-CapsuleNet

Should you include your project also in this list?
https://github.com/sekwiatkowski/awesome-capsule-networks#pytorch

**Comment by danielhavir** [comment]
Hi, I haven't inspected all of the implementations into depth but it seems they're all roughly the same age, so I assume they won't be as different. The paper got a lot of attention when it was published and so it doesn't come as a surprise that a lot of people implemented it at the same time.

Thanks for bringing the curated list to my attention, I didn't know it existed.

If you decide to compare or benchmark the implementations, I would be very curious to see the results, so please share.
